// ES6 module syntax
import LocalizedStrings from "react-localization";

const strings = new LocalizedStrings({
  en: {
    bartender: "bartender: ",
    listeningNow: "serving now",
    tapToStart: "tap to order something...  ",
    pressToStart: "press any key to order something...",
    changeStation: "change your seat",
    playPause: "play/pause",
    tweetThisStation: "share your felling",
    changeGif: "change gif",
    showVideo: "show original video",
    lowPowerMode: "low-power mode",
    closeThis: "close this",
    sayHi: "Or click here to talk with bartender",
    updates: "New stations & updates",
    arrows: "arrows",
    spacebar: "spacebar",
  },
  vi: {
    listeningNow: "đang nghe",
    tapToStart: "nhấn  để bắt đầu",
    pressToStart: "nhấn nút bất kỳ để bắt đầu",
    changeStation: "đổi kênh",
    playPause: "play/pause",
    tweetThisStation: "chia sẻ qua twitter",
    changeGif: "thay đổi gif",
    showVideo: "hiện video gốc",
    lowPowerMode: "chế độ low-power",
    closeThis: "đóng",
    sayHi: "Or click here to say hi!",
    updates: "New stations & updates",
    arrows: "phím mũi tên",
    spacebar: "phím cách",
  },
  ja: {
    bartender:"マスター：",
    tapToStart: "タップして注文してください",
    pressToStart: "キーを押して注文してください",
  },
  it: {
    listeningNow: "in ascolto ora",
    pressToStart: "premi un tasto per cominciare",
    changeStation: "cambia stazione",
    playPause: "play/pausa",
    tweetThisStation: "twitta questa stazione",
    changeGif: "cambia gif",
    showVideo: "mostra video originale",
    lowPowerMode: "modalità low-power",
    closeThis: "chiudi",
    sayHi: "Clicca qui per scriverci!",
    updates: "Nuove stazioni & update",
    arrows: "frecce",
    spacebar: "spazio",
  },
  es: {
    listeningNow: "escuchando ahora",
    pressToStart: "presionar una cualquier tecla para empezar",
    changeStation: "cambiar de estaciòn",
    playPause: "play/pause",
    tweetThisStation: "tuitear esta estaciòn",
    changeGif: "cambiar el gif",
    showVideo: "mostrar video original",
    lowPowerMode: "modo low-power",
    closeThis: "cerrar",
    sayHi: "Hacer clic aqui para contactarnos",
    updates: "Recibir actualizaciones",
    arrows: "flechas",
    spacebar: "barra espaciadora",
  },
});

export default strings;
